ExternalProject_Add(${LIBSSH2}
  URL file:///${CMAKE_CURRENT_SOURCE_DIR}/${LIBSSH2}-${LIBSSH2_VERSION}.tar.gz
  CMAKE_ARGS -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCRYPTO_BACKEND=OpenSSL
  BUILD_IN_SOURCE NO
)

ExternalProject_Get_Property(${LIBSSH2} BINARY_DIR)
set(LIBSSH2_BINARY_DIR ${BINARY_DIR})
ExternalProject_Get_Property(${LIBSSH2} SOURCE_DIR)
set(LIBSSH2_SOURCE_DIR ${SOURCE_DIR})
set(LIBSSH2_INCLUDE_DIR ${LIBSSH2_SOURCE_DIR}/include)
set(LIBSSH2_ARCHIVE_DIR ${LIBSSH2_BINARY_DIR}/src)
set(LIBSSH2_LIBRARY_DIR ${LIBSSH2_BINARY_DIR}/src)
