set(_source "${CMAKE_CURRENT_SOURCE_DIR}/${LIBSSH2}")
set(_build "${CMAKE_CURRENT_BINARY_DIR}/${LIBSSH2}")

ExternalProject_Add(${LIBSSH2}
  SOURCE_DIR ${_source}
  BINARY_DIR ${_build}
  CMAKE_ARGS -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DBUILD_DOCS=OFF -DCRYPTO_BACKEND=OpenSSL
  BUILD_IN_SOURCE NO
)

ExternalProject_Get_Property(${LIBSSH2} BINARY_DIR)
set(LIBSSH2_BINARY_DIR ${BINARY_DIR})
ExternalProject_Get_Property(${LIBSSH2} SOURCE_DIR)
set(LIBSSH2_SOURCE_DIR ${SOURCE_DIR})
set(LIBSSH2_INCLUDE_DIR ${LIBSSH2_SOURCE_DIR}/include)
set(LIBSSH2_ARCHIVE_DIR ${LIBSSH2_BINARY_DIR}/src)
set(LIBSSH2_LIBRARY_DIR ${LIBSSH2_BINARY_DIR}/src)
